### ISSUE TITLE
config-generator foundry selection crash

### ISSUE THREAD

**Issue by HardlyCodeMan** [ConsenSys/diligence-fuzzing#46]
* Fuzzing CLI version: v0.9.15
* Python version: Python 3.6.8
* Operating System: CentOS Stream 8 kernel 4.18.0-408.el8.x86_64

### Description

Selecting Foundry via the menu options or confirming the auto discovery option of Foundry crashes the application.

### What I Did

```
$ fuzz generate-config
[?] You seem to be using Foundry, is that correct? [Y/n]: y
Traceback (most recent call last):
  File "/home/sol-dev/.local/bin/fuzz", line 8, in <module>
    sys.exit(cli())
  File "/home/sol-dev/.local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/sol-dev/.local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/sol-dev/.local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sol-dev/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sol-dev/.local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/sol-dev/.local/lib/python3.6/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/sol-dev/.local/lib/python3.6/site-packages/fuzzing_cli/fuzz/generate_config.py", line 272, in fuzz_generate_config
    recreate_config(config_file)
  File "/home/sol-dev/.local/lib/python3.6/site-packages/fuzzing_cli/fuzz/generate_config.py", line 197, in recreate_config
    targets = determine_targets(ide)
  File "/home/sol-dev/.local/lib/python3.6/site-packages/fuzzing_cli/fuzz/generate_config.py", line 101, in determine_targets
    ts = style(target, fg="yellow")
  File "/home/sol-dev/.local/lib/python3.6/site-packages/click/termui.py", line 519, in style
    return "".join(bits)
TypeError: sequence item 1: expected str instance, PosixPath found
```
```
$ fuzz generate-config
[?] You seem to be using Hardhat, is that correct? [Y/n]: n
[?] Please select IDE: Foundry
   Truffle
   Hardhat
   Brownie
   Dapptools
 > Foundry

Traceback (most recent call last):
  File "/home/sol-dev/.local/bin/fuzz", line 8, in <module>
    sys.exit(cli())
  File "/home/sol-dev/.local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/sol-dev/.local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/sol-dev/.local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sol-dev/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sol-dev/.local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/sol-dev/.local/lib/python3.6/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/sol-dev/.local/lib/python3.6/site-packages/fuzzing_cli/fuzz/generate_config.py", line 272, in fuzz_generate_config
    recreate_config(config_file)
  File "/home/sol-dev/.local/lib/python3.6/site-packages/fuzzing_cli/fuzz/generate_config.py", line 197, in recreate_config
    targets = determine_targets(ide)
  File "/home/sol-dev/.local/lib/python3.6/site-packages/fuzzing_cli/fuzz/generate_config.py", line 101, in determine_targets
    ts = style(target, fg="yellow")
  File "/home/sol-dev/.local/lib/python3.6/site-packages/click/termui.py", line 519, in style
    return "".join(bits)
TypeError: sequence item 1: expected str instance, PosixPath found
```

**Comment by Nurchik** [comment]
Hi @HardlyCodeMan. Could you please give us `pip freeze`'s output?
